### ISSUE TITLE
Authentication problems

### ISSUE THREAD

**Issue by patduckless** [jonandel/ha-hildebrandglow-dcc#59]
**Describe the bug**
Authentication fails.

**To Reproduce**
Steps to reproduce the behaviour:

1. click add hub
2. enter username and password.

**Expected behaviour**
Successful Authentication

**Version**
1.4.1

**Debug log**
```
2025-10-28 11:21:56.795 ERROR (MainThread) [custom_components.hildebrandglow_dcc.config_flow] Unexpected exception: Authentication failed
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/config_flow.py", line 75, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hildebrandglow_dcc/config_flow.py", line 45, in validate_input
    glowmarkt = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        BrightClient, data["username"], data["password"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/glowmarkt/glowmarkt.py", line 70, in __init__
    self.token = self.authenticate()
                 ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/glowmarkt/glowmarkt.py", line 89, in authenticate
    raise RuntimeError("Authentication failed")
RuntimeError: Authentication failed
2025-10-28 11:22:27.891 ERROR (MainThread) [custom_components.hildebrandglow_dcc.config_flow] Unexpected exception: Authentication failed
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/config_flow.py", line 75, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hildebrandglow_dcc/config_flow.py", line 45, in validate_input
    glowmarkt = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        BrightClient, data["username"], data["password"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/glowmarkt/glowmarkt.py", line 70, in __init__
    self.token = self.authenticate()
                 ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/glowmarkt/glowmarkt.py", line 89, in authenticate
    raise RuntimeError("Authentication failed")
RuntimeError: Authentication failed
```

**Additional context**

**Comment by DejarW** [comment]
Have the same problem, authentication failed since the 27th of October

**Comment by dg362** [comment]
I have the same error, which in my logs started yesterday (27-Oct-2025) at 16:42 UK time (GMT now that clocks have gone back).
My system is set to a daily interval of 15 and a tariff interval 60.
Bright App on Android works fine with the same connection credentials.

Checking the actual upstream site of https://glowmarkt.com/login my credentials fail to login. So the error/failure is perhaps upstream and nothing to do with this integration.

**Edit**: As an isolation test, I went through the reset password process on the main website, and it stated my email address is invalid. I know that it is not because it works in the Bright App and used to work in this integration. Heavily suggests something is amiss with their database/systems.

**Edit2**: I logged out of the Bright App and tried to log in. The App stated my account was locked out due to too many failed login attempts for a period of 30 minutes. I have therefore disabled this integration in HA and will wait an hour and retry the Bright App to confirm whether that too is affected for new logins.

**Edit3**: After waiting well over an hour, and then trying to log in on the Bright App, it still states my account is locked out for too many failed login attempts. I believe that this is a GlowMarkt issue, not this integration, as authentication via both their website and their App fails.

**Comment by alsiola** [comment]
I had the same issue, however after going through the password reset flow and re-adding the integration everything is working again.

**Comment by dg362** [comment]
I tried the same approach, and was able to reset the password okay and access via the Bright App.
Within HA, I removed the integration, restarted HACS, re-added the integration, and added a hub with credentials, which now work, but in HA it states "The device is disabled by Config entry". So I'll need to work out why it's doing that. But crucially, the authentication is working again by following this approach.
**Edit**: After editing core files (after backing up) to remove all DCC entries, and a clean restart, I was able to re-add integration and re-setup the 2 devices and 4 entities per device.

**Comment by mcderd-coder** [comment]
dg362, can you tell me which core files you edited please as I have the same issue.

**Comment by mcderd-coder** [comment]
I found this on Glow market site

![Image](https://github.com/user-attachments/assets/1c01d89b-dcab-4906-9e9a-58ffc957f15b)

One small exception!

**Comment by patduckless** [comment]
For me this is solved now.

**Comment by mcderd-coder** [comment]
> For me this is solved now.

How? Did you do anything, or did it just start working?

**Comment by patduckless** [comment]
It has started working. I'd imagine my problem was related to the service disruption you posted.

**Comment by mcderd-coder** [comment]
> It has started working. I'd imagine my problem was related to the service disruption you posted.

Thanks, I have just tried restarting HA but still not working for me.

**Comment by dg362** [comment]
> dg362, can you tell me which core files you edited please as I have the same issue.

These core files are in the hidden **.storage** directory of your installation.
They are **critical** to HA functionality, and any typo or error in them will prevent HA from starting. So you need to be **very careful** editing these.

Before you do anything with these files, you **must** back them up. I would also recommend a full HA backup.

The files are named

- core.config_entries
- core.device_registry
- core.entity_registry

What I did was delete this integration, restart HA, then edit all 3 files to remove any mention of any line relating to the integration. I searched for 'Hilde', if I remember correctly.
When you are deleting lines, **make sure** to remove the comma from the end of the line not deleted, so that the JSON formatting is correctly maintained. You'll see this if you scroll to the end of the lines beforehand and note that the last line in a section has no comma.

If you have never done this before, or are in any way concerned, then **do not attempt this** because it's a quick way to break your HA installation.

**Comment by mcderd-coder** [comment]
dg362 Many thanks for that.

I managed to fix it. I could not log on to the glowmarkt.com website; it said my credentials were wrong, but I use a password manager, so I knew I was not typing them in incorrectly.

So I clicked the 'Forgot Password' link and reset my password, I could then log in, I updated my login in Home Assistant and it's working.

**Comment by cornclose** [comment]
> dg362 Many thanks for that.
> 
> I managed to fix it. I could not log on to the glowmarkt.com website; it said my credentials were wrong, but I use a password manager, so I knew I was not typing them in incorrectly.
> 
> So I clicked the 'Forgot Password' link and reset my password, I could then log in, I updated my login in Home Assistant and it's working.

How did you update the login in HA ? I don't seem to have any option for that. Tried reloading the integration but still the same - 'Authentication Failed'

Thanks

**Comment by mcderd-coder** [comment]
There was an option to add a new Hub, that asked for logon details, which worked, I then deleted the 'old' hub

**Comment by cornclose** [comment]
> There was an option to add a new Hub, that asked for logon details, which worked, I then deleted the 'old' hub

Thanks - no dice for me - just says 'Unexpected Error' following entering the credentials (which I know are correct). :-(

**Comment by mcderd-coder** [comment]
> > There was an option to add a new Hub, that asked for logon details, which worked, I then deleted the 'old' hub
> 
> Thanks - no dice for me - just says 'Unexpected Error' following entering the credentials (which I know are correct). :-(

Have you changed your password on glowmarkt.com and been able to log in to that site?

**Comment by cornclose** [comment]
> Have you changed your password on glowmarkt.com and been able to log in to that site?

I had in the background been going through their password reset process - I logged out from their site (from my old session) and tried to log back in again using the same credentials - it said incorrect password.

So I went through their password reset process, for which I also need a 4-digit token (which I have had several times..) but each time I try the password reset I get ' An error has occurred'.

I think they still have issues on the glowmarkt site..

**Comment by mcderd-coder** [comment]
> > Have you changed your password on glowmarkt.com and been able to log in to that site?
> 
> I had in the background been going through their password reset process - I logged out from their site (from my old session) and tried to log back in again using the same credentials - it said incorrect password.
> 
> So I went through their password reset process, for which I also need a 4-digit token (which I have had several times..) but each time I try the password reset I get ' An error has occurred'.
> 
> I think they still have issues on the glowmarkt site..

I found that it would not accept the password I had used for years. When I reset it, I used a shorter, simpler password because I don't think their site could handle the long, complicated one I had been using. Do the reset and use a less complex password.

Once you can get into their site, the adding of the new hub should work.

**Comment by XDREIX** [comment]
I could log into the GLOW website but not reset my password, every time I tried it stated " An error has occurred ".  Now I cannot log in at all, so obviously they have been having issues for ages. For me this has been down more than working, I wonder if I should just request for my account and data to be deleted. Pretty damn useless.

**Comment by cornclose** [comment]
> Do the reset and use a less complex password.

Yep, tried that now too - their system enforces rules on special characters and case etc - but reset to a relatively simple password that meets these requirements (otherwise you can't click 'submit') and..

'An error has occurred'

They have issues.

**Comment by mcderd-coder** [comment]
> > Do the reset and use a less complex password.
> 
> Yep, tried that now too - their system enforces rules on special characters and case etc - but reset to a relatively simple password that meets these requirements (otherwise you can't click 'submit') and..
> 
> 'An error has occurred'
> 
> They have issues.

I had been talking to Glowmarkt support and they claim they have not made any changes and do not have any problems!

So, did you get it to work with a less complex password?

**Comment by cornclose** [comment]
> So, did you get it to work with a less complex password?

No. I can't really get a less complex password than I've tried, given their stipulations. I have emailed their support team now.

**Comment by XDREIX** [comment]
Tried on the app, thought I may have better luck. I get this error "A client side error has occurred. Please review your information."
Can't go any simpler than that password. This is insane.

**Comment by mcderd-coder** [comment]
> > So, did you get it to work with a less complex password?
> 
> No. I can't really get a less complex password than I've tried, given their stipulations. I have emailed their support team now.

Good luck

**Comment by jonandel** [comment]
If its simply authentication issues with the Glow API, then you dont need to touch this integration, or delete things in HA etc.

The Integration uses the (free to use) Glow API - I do not know whether or how authentication is connected with their own Glow website - but in the log output above, the API is clearly not allowing the authentication.
The API end point is at https://api.glowmarkt.com/api/v0-1/auth

**Comment by cornclose** [comment]
> Tried on the app, thought I may have better luck. I get this error "A client side error has occurred. Please review your information." Can't go any simpler than that password.

Same.

**Comment by cornclose** [comment]
Live Incident on the glowmarkt website:

02/11/2025 08:30 PM | Due to unplanned system maintenance work on our user authentication system, login to Bright and Glow services is currently disabled. An announcement will be made here as soon as service is restored. We apologise for any inconvenience caused.

https://glowmarkt.com/support/system-incidents?incidentTimeline=live

So I guess their end after all..

**Comment by cornclose** [comment]
Now fixed and working for me. All issues appear to have been at their end. I had to read and accept new terms and conditions upon login to the glowmarkt site - so that may have broke something on some systems.

**Comment by jonandel** [comment]
Ah yes, that will do it too – I think one has to re-accept the Ts&Cs annually as it’s a condition of using the DCC data…

**Comment by paulbarnes007** [comment]
Here is my fix. I think they changed the password criteria as I had to add a special character.
Go to Glow Market. Do forgot password. Change your password (I added a special character as it would not accept previous due to rules).
I then had to delete integration. Re-added and put in new password and now live again.

**Comment by XDREIX** [comment]
I just removed the integration with HA, honestly cannot be bothered.

**Comment by zbb67** [comment]
Bit late to this but to fix mine;
Went to https://glowmarkt.com - I was already logged in presumably from a previous cookie, so logged out
Attempt to log in again, get "invalid username / password"
Follow the reset password procedure (it emails you a code)
Changed the password to exactly what it was before (it met the pwd requirements)
Now logged in the Glowmarkt website
The HA integration started working immediately afterwards, *no action in HA was needed*.

**Comment by eepyaich** [comment]
> Bit late to this but to fix mine; Went to https://glowmarkt.com - I was already logged in presumably from a previous cookie, so logged out Attempt to log in again, get "invalid username / password" Follow the reset password procedure (it emails you a code) Changed the password to exactly what it was before (it met the pwd requirements) Now logged in the Glowmarkt website The HA integration started working immediately afterwards, _no action in HA was needed_.

Just to add this worked for me too - when I got back in after the password "reset", I had to accept new Ts and Cs and the integration (which at the moment is still the old HandyHat one - my next task is to migrate to this new one!) worked straight away.
